### ISSUE TITLE
FileUploader model required files.

### ISSUE THREAD

**Issue by KenanKarav** [KenanKarav/COMS3002#2]
Determine the required files for an application,

eg. degree, id, etc.

**Comment by KenanKarav** [comment]
Required: None

**Comment by KenanKarav** [comment]
#3 parent

**Comment by shaylin-pillay** [comment]
[FileUploaderModelReqFiles.txt](https://github.com/KenanKarav/COMS3002/files/2408617/FileUploaderModelReqFiles.txt)
 Added first draft

**Comment by shaylin-pillay** [comment]
[FileUploaderModelReqFiles (1).txt](https://github.com/KenanKarav/COMS3002/files/2408619/FileUploaderModelReqFiles.1.txt)
